# Route paths of the platform API, shared by the API and the CLI.
HEALTH = "/health"
LOGIN = "/auth/login"
VERIFY = "/auth/verify"
SCHEMA = "/schema"
VALIDATE_PIPELINE = "/pipelines/validate"
DATASETS = "/datasets"
DATASET_VERSIONS = "/datasets/{name}/versions"
DATASET_VERSION = "/datasets/{name}/versions/{version}"
DATASET_DOWNLOAD = "/datasets/{name}/versions/{version}/download"
PIPELINES = "/pipelines"
CANCEL_PIPELINE = "/pipelines/{id}/cancel"
