import json
from fnmatch import fnmatchcase
from functools import cache
from pathlib import Path

# Phase algorithm -> its TRL config class.
ALGORITHMS = {"sft": "SFTConfig"}
# Training backend -> the weight methods it supports.
BACKENDS = {"hf": ("lora",)}
METHODS = sorted({method for methods in BACKENDS.values() for method in methods})

# Fields the platform owns; `*` matches any suffix.
DENIED_SETTINGS = (
    "output_dir",
    "logging_dir",
    "report_to",
    "push_to_hub",
    "hub_*",
    "save_strategy",
    "save_steps",
    "save_total_limit",
    "resume_from_checkpoint",
    "vllm_mode",
    "vllm_server_*",
)
# Adapter options vLLM can't serve.
DENIED_LORA = ("use_dora", "modules_to_save", "bias")


@cache
def trainer_config_schema(config: str) -> dict:
    """JSON Schema of a TRL/PEFT config class, generated by scripts/generate_trainer_configs.py."""
    return json.loads((Path(__file__).parent / "trainer_configs" / f"{config}.json").read_text())


def is_denied(name: str, denied: tuple[str, ...]) -> bool:
    return any(fnmatchcase(name, pattern) for pattern in denied)
